---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - name: vector
    src: git@github.com:AndrewAche/HW_ALL.git
    scm: git
    version: "1.0.1"

  - name: lighthouse
    src: git@github.com:AndrewAche/Ansible-LightHouse-role.git
    scm: git
    version: "1.1.1"
