---
clickhouse_version: "22.3.8.39"
clickhouse_amd64_packages:
  - clickhouse-common-static
clickhouse_noarch_packages:
  - clickhouse-client
  - clickhouse-server

#vector_version: "0.30.0"
vector_version: "0.21.1"
vector_amd64_packages:
  - vector
