apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80
    - name: miltitool
      port: 1180
      protocol: TCP
      targetPort: 1180
  selector:
    app: nginx_multitool
