---

clickhouse:
  hosts:
    centos7:
      ansible_connection: docker
vector:
  hosts:
    ubuntu:
      ansible_connection: docker
lighthouse:
  hosts:
    localhost:
      ansible_connection: local

